### ISSUE TITLE
Test version

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate-flutter-client#35]
Ask the developer to make the developer version available for testing before releasing a new version of the application to F-Droid. This will possibly eliminate any errors and objections to the appearance.
I also think the app version 1.0 came out a bit too fast for users.

I would also think of setting up a website for a developer, unless he already has one. He could promote his application on it.

Overall, many thanks for your contribution to the development of the application 👍. Very fast change and resources. Keep it up, the application will surely win many users 😉.

**Comment by ManeraKai** [comment]
1. From now on you can go to the [Actions](https://github.com/ManeraKai/simplytranslate-flutter-client/actions) tab and download an `Artifact` from the last commit or any further one. GitHub will build the app every time a commit has been pushed or a pull request.
2. F-Droid builds apps from the source code. There are ways to trigger it for a new version. One is from the last commit in the repo. Other is with a release file. I have the release file trigger. That's why it needs a release for the first build. Maybe should've called it 0.1.0, but it didn't have any bugs at the time and was good to go (from my testing before issues came and melatune's look).
3. I have a homeserver with a subdomain from asus.com: https://almaleehserver.asuscomm.com . It's one of the instances if you haven't noticed.
4. Thanks

**Comment by Valdnet** [comment]
1. Cool. I will try to use it.
2. This would be a solution with version 0.1.0 (I thought so too). Version 1.0 always means a full release that should be fine-tuned. Some users could install and uninstall quickly (hopefully not) 😉.
3. I will say it as a professional: If you want to appear as a good developer, of course, you must have a domain (not a subdomain) and a relevant website specifically about the application (s), not everything. But that's just advice.

> It's one of the instances if you haven't noticed.

I noticed, but did not associate and did not check :wink:.

**Comment by ManeraKai** [comment]
Actions From now on won't be triggered automatically. Because there is no need to for every single push. However, you can trigger it manually:
![image](https://user-images.githubusercontent.com/40805353/133888838-6ae1337a-f2c9-4808-a20a-8c3877838565.png)
From here, the building process will run and give you the `.apk` cupcake.
Tell me if it didn't give you permission for it.

**Comment by Valdnet** [comment]
> Tell me if it didn't give you permission for it.

I am not authorized to do so.

![obraz](https://user-images.githubusercontent.com/47037905/133889346-9d8ba128-2eb5-4a2b-a4ef-181835effa1e.png)

**Comment by ManeraKai** [comment]
Didn't find a solution. Now it's scheduled to run at 21:15 UTC every day. If you in the future wanted to run an action right now. Just tell me.
