### ISSUE TITLE
Keep color scheme

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate-flutter-client#52]
I propose to keep the colors of the application. Currently, the colors differ, for example: selecting a dictionary with loading a translation.

![obraz](https://user-images.githubusercontent.com/47037905/133934907-85b56cf2-c2bf-4be9-8ed3-0e438c45ebb2.png)

**Comment by ManeraKai** [comment]
My theory. Maybe I'm wrong:
This loading-circle chemical reaction was because I was experimenting with Flutter's theming widget. I was assigning different colors to each property to see which widgets does will it effect. I've deleted everything after. But chemical reactions are not physical reactions.
